
public class Person {
	static {
		cnt=0;
	}
	public static int cnt;
	private String id;
	private String name;
	private String mobile;
	//generate autogenerated id 
	private String generateId(String nm) {
		return cnt+nm.substring(0, 3);
	}
	public Person() {
		cnt++;
		id=generateId("XX");
		name=null;
		mobile=null;
	}
	public Person(String nm,String mob) {
		cnt++;
		this.id=generateId(nm);
		this.name=nm;
		this.mobile=mob;
	}
	
	public String toString() {
		return "Id : "+id+" Name : "+name+"mobile: "+mobile;
	}
	

}
